openapi: 3.0.3
info:
  description: OpenAPI Schema for Company registry service
  title: company-registry-service-api
  version: "0.1"
servers:
  - url: "{server}:{port}/api/backend-service"
    variables:
      server:
        default: http://localhost
        description: Server base url
      port:
        enum:
          - '443'
          - '8443'
          - '8080'
        default: '8080'
paths:
  /v1/backend-service:
    $ref: './company/v1/Companies.yaml'
  /v1/verifications/{verificationId}:
    $ref: './verification/v1/Verifications.yaml'